/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'nutri_care_mobile';
  static const String PLUGIN_VERSION = '1.0.0+3';
  static const String BIOHACKING2 = 'assets/images/biohacking2.png';
  static const String BIOHACKING3 = 'assets/images/biohacking3.png';
  static const String BIOHACKING4 = 'assets/images/biohacking4.png';
  static const String BIOHACKING_IMAGE1 = 'assets/images/biohacking_image1.png';
  static const String ONBOARDING1 = 'assets/images/onboarding1.png';
  static const String ONBOARDING2 = 'assets/images/onboarding2.png';
  static const String ONBOARDING3 = 'assets/images/onboarding3.png';
  static const String ONBOARDING4 = 'assets/images/onboarding4.png';
  static const String BROWSE1 = 'assets/png/browse1.png';
  static const String BROWSE2 = 'assets/png/browse2.png';
  static const String BROWSE3 = 'assets/png/browse3.png';
  static const String MEDICAL_IMAGE = 'assets/png/medical_image.png';
  static const String ONBOARDING_IMAGE1 = 'assets/png/onboarding_image1.png';
  static const String ONBOARDING_IMAGE2 = 'assets/png/onboarding_image2.png';
  static const String ONBOARDING_IMAGE3 = 'assets/png/onboarding_image3.png';
  static const String ONBOARDING_IMAGE4 = 'assets/png/onboarding_image4.png';
  static const String PRIVACYIMAGE = 'assets/png/privacyImage.png';
  static const String BACKWARD = 'assets/svg/backward.svg';
  static const String BIOHACKING = 'assets/svg/biohacking.svg';
  static const String BODY = 'assets/svg/body.svg';
  static const String CALORIES = 'assets/svg/calories.svg';
  static const String CARDIOLOGY = 'assets/svg/cardiology.svg';
  static const String FORWARDICON = 'assets/svg/forwardIcon.svg';
  static const String HYDRATION = 'assets/svg/hydration.svg';
  static const String LOGO = 'assets/svg/logo.svg';
  static const String RESPIRATORY = 'assets/svg/respiratory.svg';
  static const String SLEEPICON = 'assets/svg/sleepIcon.svg';
  static const String SPO2 = 'assets/svg/spo2.svg';
  static const String STRESS = 'assets/svg/stress.svg';
  static const String TIMER = 'assets/svg/timer.svg';
  static const String WEARABLE = 'assets/svg/wearable.svg';
  static const String WEIGHT = 'assets/svg/weight.svg';
}
