/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PLUGIN_NAME = 'nutri_care_mobile';
  static const String PLUGIN_VERSION = '1.0.0+3';
  static const String INTERTIGHT_BOLD = 'InterTight-Bold';
  static const String INTERTIGHT_LIGHT = 'InterTight-Light';
  static const String INTERTIGHT_MEDIUM = 'InterTight-Medium';
  static const String INTERTIGHT_REGULAR = 'InterTight-Regular';
  static const String INTERTIGHT_SEMIBOLD = 'InterTight-SemiBold';
}
