// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM5uhgv8aqdbrAfCuv0G2R_43lhWxSPWg',
    appId: '1:98824196514:web:ecbeac4b67c041682662fb',
    messagingSenderId: '98824196514',
    projectId: 'ai-nutricare',
    authDomain: 'ai-nutricare.firebaseapp.com',
    storageBucket: 'ai-nutricare.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX-g7ZdGR3R5U38hDxzRX49Y-YnsIwzRM',
    appId: '1:98824196514:android:c979dab7fa2d06052662fb',
    messagingSenderId: '98824196514',
    projectId: 'ai-nutricare',
    storageBucket: 'ai-nutricare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbhA4kz0vB3YOHo-LWxeZKccum5zLUJoA',
    appId: '1:98824196514:ios:e04aa0af3427540f2662fb',
    messagingSenderId: '98824196514',
    projectId: 'ai-nutricare',
    storageBucket: 'ai-nutricare.firebasestorage.app',
    androidClientId: '98824196514-70t0fnf1sf66308nj896i46fmabdv1jd.apps.googleusercontent.com',
    iosClientId: '98824196514-j5bampj0lq6c4ofhudqgso9440ej83cv.apps.googleusercontent.com',
    iosBundleId: 'ai.nutricare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbhA4kz0vB3YOHo-LWxeZKccum5zLUJoA',
    appId: '1:98824196514:ios:f0070fc37a8cf38c2662fb',
    messagingSenderId: '98824196514',
    projectId: 'ai-nutricare',
    storageBucket: 'ai-nutricare.firebasestorage.app',
    androidClientId: '98824196514-70t0fnf1sf66308nj896i46fmabdv1jd.apps.googleusercontent.com',
    iosClientId: '98824196514-colc4bo1qt8tlicp3d4soa2om642o55i.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutriCareMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM5uhgv8aqdbrAfCuv0G2R_43lhWxSPWg',
    appId: '1:98824196514:web:fec1e7215e5261052662fb',
    messagingSenderId: '98824196514',
    projectId: 'ai-nutricare',
    authDomain: 'ai-nutricare.firebaseapp.com',
    storageBucket: 'ai-nutricare.firebasestorage.app',
  );
}
